### ISSUE TITLE
challenge

### ISSUE THREAD

**Issue by Alex-Toucan** [MsZoezo/my-heart#2]
typical devs compile this (as a .exe, or whatever you people have on macs), and release it using the releases tab you have there.

i challenge you to complete this task

**Comment by MsZoezo** [comment]
This is far from done, and a challenge? What are you on about? x3

**Comment by Alex-Toucan** [comment]
5e55c8de3b8a8ac6f23034b0f46480b6341e1d2e << this commit

**Comment by MsZoezo** [comment]
Doesn't mean it's done? And even so randomly giving me a 'challenge' in an issue is really weird.

**Comment by Alex-Toucan** [comment]
mb i didnt know it was done

it's for funsies
